name: Run PHPUnit Tests

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      XY_PATH: /usr/bin/xz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Change as needed
          extensions: mbstring, xml, intl, curl
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit
        run: vendor/bin/phpunit
